options = optimset('MaxIter',85);
[xlp,flp,exitflag] = linprog( linobj, [objA; feasA], [objRhs; feasRhs], A, Rhs, lowerBound, upperBound, initGuess, options);

disp('Format: cvx, linprog')
disp(['Error in model constraints: ' ...
    num2str( max(abs(A*x-Rhs)) ) ', ' ...
    num2str( max(abs(A*xlp-Rhs)) )])
disp(['Error in cut constraints: ' ...
    num2str( max(max([objA;feasA]*x - [objRhs;feasRhs]),0) ) ', ' ...
    num2str( max(max([objA;feasA]*xlp - [objRhs;feasRhs]),0) ) ])
disp(['Objective values: ' ...
    num2str( cvx_optval ) ', ' ...
    num2str( flp ) ])
disp(['cvx_optval - flp = ' num2str(cvx_optval - flp)])
disp(['cvx output status: ' cvx_status])